# Generated by Django 4.2.7 on 2023-11-18 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromdesti', models.CharField(max_length=100)),
                ('todesti', models.CharField(max_length=500)),
            ],
        ),
        # migrations.CreateModel(
        #     name='Booking',
        #     fields=[

        #         ('passenger_name', models.CharField(max_length=100)),
        #         ('email', models.EmailField(max_length=254)),
        #         ('payment_mode', models.CharField(max_length=20)),
                
        #     ],
        # ),
    ]
