# Generated by Django 4.2.7 on 2023-11-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transitXpress', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('payment_mode', models.CharField(max_length=20)),
            ],
        ),
    ]
