# Generated by Django 4.2.7 on 2023-11-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transitXpress', '0003_conformation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='conformation',
            name='from_location',
            field=models.CharField(default='Default From Location', max_length=255),
        ),
        migrations.AddField(
            model_name='conformation',
            name='to_location',
            field=models.CharField(default='Default To Location', max_length=255),
        ),
    ]
