# Generated by Django 4.2.7 on 2023-11-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transitXpress', '0005_alter_conformation_from_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conformation',
            name='from_location',
            field=models.CharField(blank=True, default='Default From Location', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='conformation',
            name='to_location',
            field=models.CharField(blank=True, default='Default To Location', max_length=255, null=True),
        ),
    ]
