# Generated by Django 4.2.7 on 2024-01-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transitXpress', '0008_confirmation_delete_conformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmation',
            name='payment_mode',
            field=models.CharField(blank=True, default=1, max_length=20, null=True),
        ),
    ]
