# Generated by Django 4.2.7 on 2024-01-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transitXpress', '0009_alter_confirmation_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='arrival_time',
            field=models.TimeField(default='00.00'),
        ),
        migrations.AddField(
            model_name='feature',
            name='bus_image',
            field=models.ImageField(blank=True, null=True, upload_to='bus_images/'),
        ),
        migrations.AddField(
            model_name='feature',
            name='bus_name',
            field=models.CharField(default='RTC', max_length=100),
        ),
        migrations.AddField(
            model_name='feature',
            name='bus_number',
            field=models.CharField(default='TS08AA0000', max_length=10),
        ),
        migrations.AddField(
            model_name='feature',
            name='ticket_fare',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=8),
        ),
        migrations.AlterField(
            model_name='feature',
            name='fromdesti',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='feature',
            name='todesti',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
