# Generated by Django 4.2.7 on 2024-01-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transitXpress', '0013_alter_confirmation_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmation',
            name='booking_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
