# Generated by Django 4.2.7 on 2024-01-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transitXpress', '0014_alter_confirmation_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='arrival_time',
            field=models.TextField(default='5.00'),
        ),
    ]
