# Generated by Django 4.2.7 on 2024-01-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transitXpress', '0015_alter_feature_arrival_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmation',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='confirmation',
            name='unique_code',
            field=models.CharField(default=True, max_length=255, unique=True),
        ),
    ]
