# Generated by Django 4.2.7 on 2024-01-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transitXpress', '0016_confirmation_qr_code_confirmation_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmation',
            name='unique_code',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
