# Generated by Django 4.2.7 on 2024-01-25 18:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transitXpress', '0017_alter_confirmation_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmation',
            name='unique_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
