# Generated by Django 4.2.7 on 2024-01-25 18:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transitXpress', '0018_alter_confirmation_unique_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmation',
            name='nique_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='confirmation',
            name='qr_code',
            field=models.ImageField(blank=True, max_length=255, upload_to='qr_codes/'),
        ),
    ]
