# Generated by Django 4.2.7 on 2024-01-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transitXpress', '0019_confirmation_nique_code_alter_confirmation_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmation',
            name='nique_code',
        ),
        migrations.AlterField(
            model_name='confirmation',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes/'),
        ),
    ]
